Add Helm Chart
pagopa/io-premium-reminder-ms pull request #12
Opened 2022-10-28 09:57 UTC by AleDore

2022-10-28 10:02 UTC, pasqualedevita requested changes

2022-10-28 10:02 UTC, pasqualedevita commented on helm/values-prod01.yaml
> +  namespace: "payments"
```suggestion
  namespace: "messages"
```

2022-10-28 10:03 UTC, pasqualedevita approved these changes

2022-10-28 10:06 UTC, pasqualedevita requested changes

2022-10-28 10:06 UTC, pasqualedevita commented on helm/values-beta.yaml
> +    host: "weubeta.reminder.internal.io.pagopa.it"
```suggestion
    host: "weubeta.messages.internal.io.pagopa.it"
```

2022-10-28 10:06 UTC, pasqualedevita commented on helm/values-prod01.yaml
> +    host: "weuprod01.reminder.internal.io.pagopa.it"
```suggestion
    host: "weuprod01.messages.internal.io.pagopa.it"
```

2022-10-28 13:38 UTC, AleDore commented
@giporro: Can we add specific application properties on helm's values?

2022-10-31 08:56 UTC, giporro approved these changes, later dismissed
- add application properties
- added variables for kafka implementation. please add secrets for enviroments

2022-11-07 17:25 UTC, merged